# Generated by Django 5.1.3 on 2025-02-22 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignEaseApp', '0002_alter_submission_assignment_alter_submission_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classstudent',
            constraint=models.UniqueConstraint(fields=('student', 'class_assigned'), name='unique_student_class'),
        ),
    ]
